import os
from dotenv import load_dotenv

load_dotenv()

def get_env_variable(var_name):
    return os.getenv(var_name)

#load environment variables
LINK_360 = get_env_variable('LINK_360')
LINK_ADITYA_BIRLA_CAPITAL = get_env_variable('LINK_ADITYA_BIRLA_CAPITAL')
LINK_BOI = get_env_variable('LINK_BOI')
LINK_BARODA = get_env_variable('LINK_BARODA')
LINK_CANARA_ROBECO = get_env_variable('LINK_CANARA_ROBECO')
LINK_DSP = get_env_variable('LINK_DSP')
LINK_EDELWEISS = get_env_variable('LINK_EDELWEISS')
LINK_FRANKLIN_TEMPLETON = get_env_variable('LINK_FRANKLIN_TEMPLETON')
LINK_GROWW = get_env_variable('LINK_GROWW')
LINK_HDFC = get_env_variable('LINK_HDFC')
LINK_HELIOS = get_env_variable('LINK_HELIOS')
LINK_HSBC = get_env_variable('LINK_HSBC')
LINK_ICICI = get_env_variable('LINK_ICICI')
LINK_INVESCO = get_env_variable('LINK_INVESCO')
LINK_ITIAMC = get_env_variable('LINK_ITIAMC')
LINK_JM_FINANCIAL = get_env_variable('LINK_JM_FINANCIAL')
LINK_BANDHAN = get_env_variable('LINK_BANDHAN')
LINK_AXIS = get_env_variable('LINK_AXIS')
LINK_MOTILAL = get_env_variable('LINK_MOTILAL')
LINK_NJ = get_env_variable('LINK_NJ')
LINK_OLD_BRIDGE_ASSET = get_env_variable('LINK_OLD_BRIDGE_ASSET')
LINK_PPFAS = get_env_variable('LINK_PPFAS')
LINK_KOTAK = get_env_variable('LINK_KOTAK')
LINK_SAMCO = get_env_variable('LINK_SAMCO')
LINK_QUANT = get_env_variable('LINK_QUANT')
LINK_PGIM = get_env_variable('LINK_PGIM')
LINK_NIPPON = get_env_variable('LINK_NIPPON')
LINK_NAVI = get_env_variable('LINK_NAVI')
LINK_MIRAE = get_env_variable('LINK_MIRAE')
LINK_SBI = get_env_variable('LINK_SBI')
LINK_SUNDARAM = get_env_variable('LINK_SUNDARAM')
LINK_TRUST = get_env_variable('LINK_TRUST')
LINK_WHITEOAK = get_env_variable('LINK_WHITEOAK')
LINK_TAURUS = get_env_variable('LINK_TAURUS')
LINK_UNION = get_env_variable('LINK_UNION')
LINK_ZERODHA = get_env_variable('LINK_ZERODHA')
LINK_LIC = get_env_variable('LINK_LIC')
LINK_MAHINDRA = get_env_variable('LINK_MAHINDRA')
LINK_SHRIRAM = get_env_variable('LINK_SHRIRAM')
LINK_UTI = get_env_variable('LINK_UTI')
LINK_TATA = get_env_variable('LINK_TATA')
LINK_QUANTUM = get_env_variable('LINK_QUANTUM')
LINK_XLS_TO_XLSX=get_env_variable('LINK_XLS_TO_XLSX')
TOKEN = get_env_variable('TOKEN')